services:
  web:
    build:
      context: docker_config/web/
    container_name: matsu-web
    ports:
      - 18080:80
    working_dir: /var/www
    volumes:
      - ./src/www/:/var/www
      - framework_data:/var/www/storage/framework
      - vendor_data:/var/www/vendor
    depends_on:
      - db
  db:
    build:
      context: docker_config/db/
    container_name: matsu-db
    volumes:
      # ここにdbデータがある（バックアップを最後にvolumeする）
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=matsu
      - MYSQL_HOST=localhost
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_user_pass
      - MYSQL_ROOT_PASSWORD=test_root_pass
      - TZ=Asia/Tokyo
    ports:
      - 13306:3306
volumes:
    db_data:
    framework_data:
    vendor_data:
